---

- name: Disable IPv6
  template: src=etc/sysctl.d/disableipv6.conf.j2 dest=/etc/sysctl.d/disableipv6.conf owner=root group=root mode=0644
  register: networking_register_disable_ipv6

- name: Disable IPv6 via sysctl
  command: sysctl net.ipv6.conf.all.disable_ipv6=1
  when: networking_register_disable_ipv6.changed

- name: Copy hosts file
  template: src=etc/hosts.j2 dest=/etc/hosts owner=root group=root mode=0644

- name: Copy resolv.conf
  tags: networking::resolv
  template: src=etc/resolv.conf.j2 dest=/etc/resolv.conf owner=root group=root mode=0644
  when: not networking_write_resolvconf is defined or networking_write_resolvconf

- name: Configure main interface file
  template:
    src: 'etc/network/interfaces.j2'
    dest: '/etc/network/interfaces'
    mode: 0644

- name: Create interfaces directory
  file:
    path: '/etc/network/interfaces.d'
    state: directory
    owner: root
    mode: 0755

- name: Configure interfaces
  tags: networking::interfaces
  template:
    src: 'etc/network/interfaces.d/net-name.j2'
    dest: '/etc/network/interfaces.d/{{ item.name }}'
    mode: 0644
  with_items: '{{ networking_interfaces }}'
  when: networking_interfaces is defined

